# install.ps1 - VS Code "Dark Modern" theme for lazygit (Windows installer)
# https://github.com/Makihataima-Ken/lazygit-vscode-themes
#
# From a clone (Windows PowerShell 5.1 or PowerShell 7):
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\install.ps1
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\install.ps1 -Mode Append
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\install.ps1 -Uninstall
#
# Without a clone:
#   irm https://raw.githubusercontent.com/OWNER/lazygit-vscode-dark-modern/main/install.ps1 | iex
#   & ([scriptblock]::Create((irm https://raw.githubusercontent.com/OWNER/lazygit-vscode-dark-modern/main/install.ps1))) -Mode Append
#   & ([scriptblock]::Create((irm https://raw.githubusercontent.com/OWNER/lazygit-vscode-dark-modern/main/install.ps1))) -Uninstall
#
# Parameters:
#   -Mode Overlay   (default) Copy the theme to <config dir>\themes\vscode-dark-modern.yml and
#                   put it FIRST in the User environment variable LG_CONFIG_FILE, followed by
#                   your own config.yml, so your own settings win over the theme.
#   -Mode Append    Append the theme to config.yml between marker comments instead, for
#                   lazygit launched from places that do not see environment variables.
#                   Refuses (changes nothing) if config.yml already has a top-level gui: key.
#   -Uninstall      Undo both modes. config.yml itself is never deleted.
#   -ConfigDir DIR  lazygit config directory (default: output of lazygit --print-config-dir).
#   -NoPersist      Write LG_CONFIG_FILE of the current process only; nothing is written to
#                   the registry. For trying it out and for tests. Run it in the current
#                   session (.\install.ps1 -NoPersist), not with `powershell -File`.
#
# Everything runs inside one function, removed again at the end, so the script's own variables
# never reach the caller and the caller's $ErrorActionPreference is never changed. One limit:
# `irm ... | iex` runs the param() block below in the caller's scope, so variables named
# $Uninstall, $Mode, $ConfigDir or $NoPersist that already exist in that scope are reset to
# these defaults. `& ([scriptblock]::Create((irm ...)))` runs in a child scope and has no such
# effect. This script never calls `exit`.

param(
    [switch]$Uninstall,
    [ValidateSet('Overlay', 'Append')]
    [string]$Mode = 'Overlay',
    [string]$ConfigDir,
    [switch]$NoPersist
)

function Install-LazygitVSCodeDarkModern {
    param(
        [switch]$Uninstall,
        [ValidateSet('Overlay', 'Append')]
        [string]$Mode = 'Overlay',
        [string]$ConfigDir,
        [switch]$NoPersist
    )

    Set-StrictMode -Version 2.0
    $ErrorActionPreference = 'Stop'

    $ThemeId     = 'vscode-dark-modern'
    $Prefix      = '[lazygit-vscode-dark-modern]'
    $BeginMarker = '# >>> lazygit-vscode-dark-modern >>>'
    $EndMarker   = '# <<< lazygit-vscode-dark-modern <<<'
    $RepoUrl     = 'https://github.com/Makihataima-Ken/lazygit-vscode-themes'
    $InstallUrl  = 'https://raw.githubusercontent.com/OWNER/lazygit-vscode-dark-modern/main/install.ps1'
    $ShInstall   = 'curl -fsSL https://raw.githubusercontent.com/OWNER/lazygit-vscode-dark-modern/main/install.sh | sh'
    $EnvName     = 'LG_CONFIG_FILE'
    $Utf8NoBom   = New-Object System.Text.UTF8Encoding $false
    # config.yml is edited as ISO-8859-1 text: one char per byte, so every byte outside the
    # marker block (BOM, CRLF, invalid UTF-8, ...) is written back exactly as it was read.
    $Latin1      = [System.Text.Encoding]::GetEncoding(28591)
    $Latin1Bom   = [string][char]0xEF + [char]0xBB + [char]0xBF
    $Changes     = New-Object System.Collections.Generic.List[string]
    $ScriptDir   = $PSScriptRoot

    # Test seam (tests/test-install.ps1): with LGVDM_TEST_ENV_KEY set to a registry key under
    # HKCU:\Software\lgvdm-test\, the User and Machine LG_CONFIG_FILE values are read from and
    # written to its User and Machine subkeys instead of the real environment.
    $TestEnvKey  = [string]$env:LGVDM_TEST_ENV_KEY
    if ($TestEnvKey) {
        if (-not $TestEnvKey.StartsWith('HKCU:\Software\lgvdm-test\', [System.StringComparison]::OrdinalIgnoreCase) -or
            $TestEnvKey.Contains('..') -or $TestEnvKey.Contains('/')) {
            throw "$Prefix LGVDM_TEST_ENV_KEY must name a key under HKCU:\Software\lgvdm-test\ (it is only for tests). Nothing was changed."
        }
    }

# BEGIN EMBEDDED THEME (generated by tools/sync-theme.sh - do not edit by hand)
$EmbeddedTheme = @'
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
#
# VS Code "Dark Modern" theme for lazygit
# https://github.com/Makihataima-Ken/lazygit-vscode-themes
#
# Colors come from VS Code's own theme sources (microsoft/vscode):
#   extensions/theme-defaults/themes/dark_modern.json  (workbench colors)
#   extensions/git/package.json                          (gitDecoration.* defaults)
#   src/vs/platform/theme/common/colors/listColors.ts    (list selection defaults)
#
# Rules for editing this file:
#   - Every color value is a YAML list: ['#RRGGBB'] or ['#RRGGBB', bold].
#   - Hex values MUST be quoted. An unquoted "- #0078D4" is a YAML comment.
#   - Only #RGB / #RRGGBB work. lazygit rejects #RRGGBBAA (alpha) and draws white.
#   - One color per list; the only extra attributes are bold / underline / reverse.
#
# lazygit cannot paint the background. Set your terminal background to
# #181818 (VS Code panel terminal) or #1F1F1F (editor), and use the matching
# ANSI palette from extras/ so hard-coded ANSI colors (staged files, commit
# hashes, diff +/-) match VS Code too.

gui:
  # VS Code panels have square corners.
  border: single

  theme:
    # focusBorder / tab.activeBorderTop
    activeBorderColor:
      - '#0078D4'
      - bold
    # activityBar.inactiveForeground: unfocused chrome, still >= 4.5:1 on #181818 / #1F1F1F
    inactiveBorderColor:
      - '#868686'
    # editorWarning.foreground / list.warningForeground (VS Code amber)
    searchingActiveBorderColor:
      - '#CCA700'
      - bold
    # textLink.foreground (keybinding hints in the bottom bar)
    optionsTextColor:
      - '#4DAAFC'
    # list.activeSelectionBackground
    selectedLineBgColor:
      - '#04395E'
    # list.inactiveSelectionBackground
    inactiveViewSelectedLineBgColor:
      - '#37373D'
    # button.foreground on button.background
    cherryPickedCommitFgColor:
      - '#FFFFFF'
    cherryPickedCommitBgColor:
      - '#0078D4'
    # editor.findMatchBackground (no visible effect in lazygit 0.65, kept for newer versions)
    markedBaseCommitFgColor:
      - '#FFFFFF'
    markedBaseCommitBgColor:
      - '#9E6A03'
    # gitDecoration.modifiedResourceForeground
    unstagedChangesColor:
      - '#E2C08D'
    # foreground
    defaultFgColor:
      - '#CCCCCC'
'@
# END EMBEDDED THEME

    # ---------------------------------------------------------------- helpers

    function Write-Info([string]$Message) { Write-Host "$Prefix $Message" }

    function Write-Warn([string]$Message) { Write-Warning "$Prefix $Message" }

    function Add-Change([string]$Message) { $Changes.Add($Message) }

    function Test-SameText([string]$Left, [string]$Right) {
        return [string]::Equals($Left, $Right, [System.StringComparison]::Ordinal)
    }

    function Test-IsWindowsHost {
        if ($PSVersionTable.PSEdition -eq 'Desktop') { return $true }
        $isWin = Get-Variable -Name IsWindows -ValueOnly -ErrorAction SilentlyContinue
        if ($null -eq $isWin) { return $true }
        return [bool]$isWin
    }

    function Write-TextFile([string]$Path, [string]$Text) {
        [System.IO.File]::WriteAllText($Path, $Text, $Utf8NoBom)
    }

    function Read-ConfigText([string]$Path) {
        return $Latin1.GetString([System.IO.File]::ReadAllBytes($Path))
    }

    function Write-ConfigText([string]$Path, [string]$Text) {
        [System.IO.File]::WriteAllBytes($Path, $Latin1.GetBytes($Text))
    }

    # For config text read by Read-ConfigText: the encoding's name if it is UTF-16 or UTF-32
    # (a byte order mark, or NUL bytes), else ''. Windows PowerShell 5.1's > and Out-File write
    # UTF-16LE. Such a file cannot be edited byte-wise: the theme block is UTF-8.
    function Get-WideEncodingName([string]$Text) {
        $nul = [string][char]0
        if ($Text.StartsWith([string][char]0xFF + [char]0xFE + $nul + $nul, [System.StringComparison]::Ordinal)) { return 'UTF-32LE' }
        if ($Text.StartsWith($nul + $nul + [char]0xFE + [char]0xFF, [System.StringComparison]::Ordinal)) { return 'UTF-32BE' }
        if ($Text.StartsWith([string][char]0xFF + [char]0xFE, [System.StringComparison]::Ordinal)) { return 'UTF-16LE' }
        if ($Text.StartsWith([string][char]0xFE + [char]0xFF, [System.StringComparison]::Ordinal)) { return 'UTF-16BE' }
        if ($Text.Contains($nul)) { return 'UTF-16 or UTF-32 (it contains NUL bytes)' }
        return ''
    }

    # Config text for key checks only (never written back); UTF-16/UTF-32 is decoded by its BOM.
    function Read-ConfigScanText([string]$Path) {
        $text = Read-ConfigText $Path
        if (Get-WideEncodingName $text) { return [System.IO.File]::ReadAllText($Path) }
        return $text
    }

    # A PowerShell single-quoted string literal (also doubles the typographic quotes).
    function ConvertTo-QuotedArgument([string]$Text) {
        return "'" + [System.Management.Automation.Language.CodeGeneration]::EscapeSingleQuotedStringContent($Text) + "'"
    }

    # LF line endings, no BOM, exactly one trailing newline.
    function ConvertTo-ThemeText([string]$Text) {
        $t = $Text -replace "`r`n", "`n"
        if ($t.Length -gt 0 -and $t[0] -eq [char]0xFEFF) { $t = $t.Substring(1) }
        $t = $t -replace "`n+\z", ''
        return $t + "`n"
    }

    function Resolve-FullPath([string]$Path) {
        $p = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
        $p = [System.IO.Path]::GetFullPath($p)
        if ($p.Length -gt 3) { $p = $p.TrimEnd([char[]]@('\', '/')) }
        return $p
    }

    function Get-PathKey([string]$Path) {
        return ($Path -replace '/', '\').TrimEnd([char[]]@('\')).ToLowerInvariant()
    }

    function Test-SamePath([string]$Left, [string]$Right) {
        return (Test-SameText (Get-PathKey $Left) (Get-PathKey $Right))
    }

    function Test-SamePathList($LeftList, $RightList) {
        $l = @($LeftList)
        $r = @($RightList)
        if ($l.Count -ne $r.Count) { return $false }
        for ($i = 0; $i -lt $l.Count; $i++) {
            if (-not (Test-SamePath $l[$i] $r[$i])) { return $false }
        }
        return $true
    }

    # LG_CONFIG_FILE value -> entries (split on ',', trimmed, empty entries dropped).
    # Callers wrap the result in @(): a single entry would otherwise unroll to a string.
    function Split-ConfigList([string]$Value) {
        $result = New-Object System.Collections.Generic.List[string]
        if ($Value) {
            foreach ($part in $Value.Split(',')) {
                $item = $part.Trim()
                if ($item.Length -gt 0) { $result.Add($item) }
            }
        }
        return $result.ToArray()
    }

    function Test-FileExists([string]$Path) {
        try { return [bool](Test-Path -LiteralPath $Path -PathType Leaf) } catch { return $false }
    }

    # First line of `lazygit --print-config-dir`, or $null.
    function Get-LazygitConfigDir {
        $cmd = Get-Command -Name 'lazygit' -CommandType Application -ErrorAction SilentlyContinue |
            Select-Object -First 1
        if ($null -eq $cmd) { return $null }
        $ErrorActionPreference = 'Continue'
        $PSNativeCommandUseErrorActionPreference = $false
        $savedEncoding = $null
        try {
            # lazygit prints UTF-8; decode it as such (user names with non-ASCII letters).
            $savedEncoding = [Console]::OutputEncoding
            [Console]::OutputEncoding = $Utf8NoBom
        } catch { $savedEncoding = $null }
        $lines = @()
        try {
            $lines = @(& $cmd.Path --print-config-dir 2>$null)
        } catch {
            $lines = @()
        } finally {
            if ($null -ne $savedEncoding) {
                try { [Console]::OutputEncoding = $savedEncoding } catch { }
            }
        }
        foreach ($line in $lines) {
            $candidate = "$line".Trim()
            if ($candidate.Length -eq 0) { continue }
            try {
                if ([System.IO.Path]::IsPathRooted($candidate)) { return $candidate }
            } catch { }
            return $null
        }
        return $null
    }

    # An XDG_* path the way lazygit's xdg library (github.com/adrg/xdg) takes it: a leading
    # %USERPROFILE% is expanded, and anything that is not an absolute path is ignored ('').
    function ConvertFrom-XdgPath([string]$Path) {
        $p = ([string]$Path).Replace('"', '')
        if ($p.StartsWith('%USERPROFILE%', [System.StringComparison]::Ordinal)) {
            $p = [Environment]::GetFolderPath('UserProfile') + '\' + $p.Substring(13).TrimStart([char[]]@('\', '/'))
        }
        if ($p -match '^(?:[A-Za-z]:[\\/]|[\\/]{2})') { return $p }
        return ''
    }

    # The config directory lazygit would use, for when lazygit cannot be asked. Mirrors lazygit's
    # findConfigFile (pkg/config/app_config.go): CONFIG_DIR; else the first directory holding
    # jesseduffield\lazygit\config.yml, then lazygit\config.yml, in XDG_CONFIG_HOME (default:
    # Local AppData) and then in each XDG_CONFIG_DIRS entry (default: ProgramData, then Roaming
    # AppData); else <XDG_CONFIG_HOME>\lazygit.
    function Get-DefaultConfigDir {
        if ($env:CONFIG_DIR) { return $env:CONFIG_DIR }
        $configHome = ConvertFrom-XdgPath $env:XDG_CONFIG_HOME
        if (-not $configHome) { $configHome = [Environment]::GetFolderPath('LocalApplicationData') }
        if (-not $configHome) { $configHome = $env:LOCALAPPDATA }
        $configDirs = @()
        foreach ($d in ([string]$env:XDG_CONFIG_DIRS).Split(';')) {
            $x = ConvertFrom-XdgPath $d
            if ($x) { $configDirs += $x }
        }
        if ($configDirs.Count -eq 0) {
            $configDirs = @(@([Environment]::GetFolderPath('CommonApplicationData'), [Environment]::GetFolderPath('ApplicationData')) | Where-Object { $_ })
        }
        foreach ($rel in @('jesseduffield\lazygit', 'lazygit')) {
            foreach ($base in @($configHome) + $configDirs) {
                $found = $false
                try {
                    $dir = [System.IO.Path]::Combine($base, $rel)
                    $found = Test-Path -LiteralPath ([System.IO.Path]::Combine($dir, 'config.yml'))
                } catch { $found = $false }
                if ($found) { return $dir }
            }
        }
        return [System.IO.Path]::Combine($configHome, 'lazygit')
    }

    function Get-ThemeText {
        $localTheme = ''
        if ($ScriptDir) {
            $localTheme = [System.IO.Path]::Combine([System.IO.Path]::Combine($ScriptDir, 'themes'), "$ThemeId.yml")
        }
        if ($localTheme -and (Test-FileExists $localTheme)) {
            Write-Info "Theme source: $localTheme"
            return (ConvertTo-ThemeText ([System.IO.File]::ReadAllText($localTheme, $Utf8NoBom)))
        }
        Write-Info 'Theme source: copy embedded in this script'
        return (ConvertTo-ThemeText $EmbeddedTheme)
    }

    # Lines of a config text, each keeping its own line terminator.
    function Get-ConfigLines([string]$Text) {
        if ($Text.Length -eq 0) { return }
        foreach ($piece in [regex]::Split($Text, '(?<=\n)')) {
            if ($piece.Length -gt 0) { $piece }
        }
    }

    # Line content without terminator / trailing blanks (and without a BOM on line 1).
    function Get-LineText([string]$Line, [int]$Index) {
        $t = $Line.TrimEnd()
        if ($Index -eq 0 -and $t.StartsWith($Latin1Bom, [System.StringComparison]::Ordinal)) {
            $t = $t.Substring(3)
        }
        return $t
    }

    # Marker blocks as objects { Start; End } (line indexes, End = -1 if the end marker is missing).
    function Find-MarkerBlocks($Lines) {
        $i = 0
        while ($i -lt $Lines.Count) {
            if (Test-SameText (Get-LineText $Lines[$i] $i) $BeginMarker) {
                $j = $i + 1
                while ($j -lt $Lines.Count -and -not (Test-SameText (Get-LineText $Lines[$j] $j) $EndMarker)) { $j++ }
                if ($j -ge $Lines.Count) {
                    New-Object PSObject -Property @{ Start = $i; End = -1 }
                    return
                }
                New-Object PSObject -Property @{ Start = $i; End = $j }
                $i = $j + 1
            } else {
                $i++
            }
        }
    }

    function Get-BlockLineSet($Blocks) {
        $set = @{}
        foreach ($b in @($Blocks)) {
            for ($k = $b.Start; $k -le $b.End; $k++) { $set[$k] = $true }
        }
        return $set
    }

    # Text with every marker block removed; $Replacement goes where the first block was.
    function Join-WithoutBlocks($Lines, $Blocks, [string]$Replacement) {
        $skip = Get-BlockLineSet $Blocks
        $sb = New-Object System.Text.StringBuilder
        $inserted = $false
        for ($i = 0; $i -lt $Lines.Count; $i++) {
            if ($skip.ContainsKey($i)) {
                if (-not $inserted) {
                    [void]$sb.Append($Replacement)
                    $inserted = $true
                }
                continue
            }
            [void]$sb.Append($Lines[$i])
        }
        return $sb.ToString()
    }

    function Test-TopLevelGui($Lines, $Blocks) {
        $skip = Get-BlockLineSet $Blocks
        for ($i = 0; $i -lt $Lines.Count; $i++) {
            if ($skip.ContainsKey($i)) { continue }
            if ((Get-LineText $Lines[$i] $i) -cmatch '^(gui|"gui"|''gui'')\s*:') { return $true }
        }
        return $false
    }

    # True if a `theme:` key appears inside a top-level `gui:` mapping.
    function Test-GuiThemeKey($Lines) {
        $inGui = $false
        for ($i = 0; $i -lt $Lines.Count; $i++) {
            $line = Get-LineText $Lines[$i] $i
            if ($line -cmatch '^(gui|"gui"|''gui'')\s*:') { $inGui = $true; continue }
            if ($line -cmatch '^[^\s#]') { $inGui = $false; continue }
            if ($inGui -and $line -cmatch '^\s+(theme|"theme"|''theme'')\s*:') { return $true }
        }
        return $false
    }

    function Backup-ConfigFile {
        $bak = $ConfigFile + '.bak'
        [System.IO.File]::Copy($ConfigFile, $bak, $true)
        # Copy keeps a read-only attribute, which would block the next backup.
        $attrs = [System.IO.File]::GetAttributes($bak)
        if (($attrs -band [System.IO.FileAttributes]::ReadOnly) -ne 0) {
            [System.IO.File]::SetAttributes($bak, ($attrs -band (-bnot [System.IO.FileAttributes]::ReadOnly)))
        }
        Add-Change "Backed up the previous $ConfigFile to $bak"
    }

    function Test-ListsTheme([string]$Value) {
        return (@(Split-ConfigList $Value | Where-Object { Test-SamePath $_ $ThemeDest }).Count -gt 0)
    }

    # Uninstall helper: $null = leave the variable alone (theme not listed),
    # '' = delete the variable, anything else = the new value.
    # $MachineValue: the Machine-wide value that deleting a User variable would expose.
    function Get-UninstallValue([string]$Value, [string]$MachineValue) {
        $entries = @(Split-ConfigList $Value)
        $kept = @($entries | Where-Object { -not (Test-SamePath $_ $ThemeDest) })
        if ($kept.Count -eq $entries.Count) { return $null }
        if ($kept.Count -eq 0) { return '' }
        $machineEntries = @(Split-ConfigList $MachineValue)
        if ($machineEntries.Count -gt 0) {
            # Delete only when that leaves the same list in effect; otherwise keep shadowing it.
            if (Test-SamePathList $kept $machineEntries) { return '' }
            return ($kept -join ',')
        }
        if ($kept.Count -eq 1 -and (Test-SamePath $kept[0] $ConfigFile)) { return '' }
        return ($kept -join ',')
    }

    # User / Machine LG_CONFIG_FILE ('' when not set); see $TestEnvKey.
    function Get-StoredValue([string]$Scope) {
        if ($TestEnvKey) {
            $item = $null
            try { $item = Get-ItemProperty -LiteralPath "$TestEnvKey\$Scope" -Name $EnvName -ErrorAction Stop } catch { $item = $null }
            if ($null -eq $item) { return '' }
            return [string]$item.$EnvName
        }
        return [string][Environment]::GetEnvironmentVariable($EnvName, $Scope)
    }

    function Set-UserValue([string]$Value) {
        if ($TestEnvKey) {
            $key = "$TestEnvKey\User"
            if (-not (Test-Path -LiteralPath $key)) { [void](New-Item -Path $key -Force) }
            [void](New-ItemProperty -LiteralPath $key -Name $EnvName -Value $Value -PropertyType String -Force)
            return
        }
        [Environment]::SetEnvironmentVariable($EnvName, $Value, 'User')
    }

    function Remove-UserVariable {
        $key = 'HKCU:\Environment'
        if ($TestEnvKey) {
            $key = "$TestEnvKey\User"
        } else {
            [Environment]::SetEnvironmentVariable($EnvName, [NullString]::Value, 'User')
        }
        # .NET 9 (PowerShell 7.5) may store an empty value instead of deleting it.
        $still = $null
        try { $still = Get-ItemProperty -LiteralPath $key -Name $EnvName -ErrorAction Stop } catch { $still = $null }
        if ($null -ne $still) {
            Remove-ItemProperty -LiteralPath $key -Name $EnvName -ErrorAction SilentlyContinue
        }
    }

    function Get-UndoCommand {
        $undoArgs = ''
        if ($ConfigDir) { $undoArgs += " -ConfigDir $(ConvertTo-QuotedArgument $TargetDir)" }
        if ($NoPersist) { $undoArgs += ' -NoPersist' }
        if ($ScriptDir) {
            $uninstaller = [System.IO.Path]::Combine($ScriptDir, 'uninstall.ps1')
            if (Test-FileExists $uninstaller) {
                # -NoPersist changed only this PowerShell process, so its undo must run in this
                # process too: a `powershell -File` child would only clean up its own copy.
                if ($NoPersist) { return "& $(ConvertTo-QuotedArgument $uninstaller)$undoArgs" }
                return "powershell -NoProfile -ExecutionPolicy Bypass -File `"$uninstaller`"$undoArgs"
            }
        }
        return "& ([scriptblock]::Create((irm $InstallUrl))) -Uninstall$undoArgs"
    }

    function Write-Summary([string[]]$Notes) {
        Write-Host ''
        if ($Changes.Count -eq 0) {
            Write-Info 'Nothing changed: everything was already in place.'
        } else {
            Write-Info 'Changes:'
            foreach ($c in $Changes) { Write-Host "  - $c" }
        }
        foreach ($n in @($Notes)) { if ($n) { Write-Info $n } }
    }

    # ---------------------------------------------------------------- overlay mode

    function Invoke-OverlayInstall {
        if ($TargetDir.Contains(',')) {
            throw "$Prefix The config directory '$TargetDir' contains a comma, which LG_CONFIG_FILE (a comma-separated list) cannot express. Use -Mode Append, or -ConfigDir with a path without commas. Nothing was changed."
        }
        $themeText = Get-ThemeText
        [void][System.IO.Directory]::CreateDirectory($ThemesDir)

        if (Test-FileExists $ThemeDest) {
            $oldB64 = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($ThemeDest))
            $newB64 = [Convert]::ToBase64String($Utf8NoBom.GetBytes($themeText))
            if (Test-SameText $oldB64 $newB64) {
                Write-Info "Theme file already up to date: $ThemeDest"
            } else {
                Write-TextFile $ThemeDest $themeText
                Add-Change "Updated the theme file $ThemeDest"
            }
        } else {
            Write-TextFile $ThemeDest $themeText
            Add-Change "Installed the theme file $ThemeDest"
        }

        # Base list: the value we are about to replace.
        $machine = ''
        if ($NoPersist) {
            $current = [string]$env:LG_CONFIG_FILE
            $base = $current
        } else {
            $current = Get-StoredValue 'User'
            $machine = Get-StoredValue 'Machine'
            $base = $current
            if (@(Split-ConfigList $current).Count -eq 0 -and $machine) { $base = $machine }
        }
        $entries = @(Split-ConfigList $base | Where-Object { -not (Test-SamePath $_ $ThemeDest) })
        if ($entries.Count -eq 0) { $entries = @($ConfigFile) }
        $newValue = (@($ThemeDest) + $entries) -join ','

        # config.yml matters only when LG_CONFIG_FILE lists it; the last listed file wins.
        $listsConfig = (@($entries | Where-Object { Test-SamePath $_ $ConfigFile }).Count -gt 0)
        if ($listsConfig -and -not (Test-Path -LiteralPath $ConfigFile)) {
            Write-TextFile $ConfigFile ''
            Add-Change "Created an empty $ConfigFile (your own settings go there and override the theme)"
        }

        if ($NoPersist) {
            if (Test-SameText $current $newValue) {
                Write-Info "LG_CONFIG_FILE of this process is already up to date."
            } else {
                $env:LG_CONFIG_FILE = $newValue
                Add-Change "Set LG_CONFIG_FILE for this PowerShell process only (-NoPersist): $newValue"
            }
        } else {
            $processBefore = [string]$env:LG_CONFIG_FILE
            if (Test-SameText $current $newValue) {
                Write-Info "User environment variable LG_CONFIG_FILE is already up to date."
            } else {
                Set-UserValue $newValue
                $was = '(was not set)'
                if ($current) { $was = "(was: $current)" }
                Add-Change "Set the User environment variable LG_CONFIG_FILE = $newValue $was"
            }
            $env:LG_CONFIG_FILE = $newValue
            if ($processBefore -and -not (Test-SameText $processBefore $current) -and
                -not (Test-SameText $processBefore $machine) -and -not (Test-SameText $processBefore $newValue)) {
                Write-Warn "This session had LG_CONFIG_FILE=$processBefore, which is not the stored User value. If your PowerShell profile or another tool sets LG_CONFIG_FILE, put $ThemeDest first in that value too, or the theme will not load there."
            }
        }

        foreach ($entry in $entries) {
            if (-not (Test-FileExists $entry)) {
                Write-Warn "LG_CONFIG_FILE lists $entry, which does not exist. lazygit refuses to start while a listed file is missing: create it or remove it from LG_CONFIG_FILE."
                continue
            }
            $lines = @(Get-ConfigLines (Read-ConfigScanText $entry))
            if (Test-GuiThemeKey $lines) {
                if (@(Find-MarkerBlocks $lines).Count -gt 0) {
                    Write-Warn "$entry still contains the theme block added by -Mode Append. It is loaded after the theme file and overrides it. Run with -Uninstall, then install again, to keep only one copy."
                } else {
                    Write-Warn "$entry sets gui.theme. It is loaded after the theme file, so those keys override the theme. Remove the gui.theme keys you want the theme to control."
                }
            }
        }

        $notes = @()
        $notes += "To undo: $(Get-UndoCommand)"
        if ($NoPersist) {
            $notes += 'Next: -NoPersist changed only this PowerShell process; only lazygit started from it uses the theme.'
        } else {
            $notes += 'Next: open a NEW terminal (running programs keep the old environment), then start lazygit.'
        }
        if ($listsConfig) {
            $notes += "Customize in $ConfigFile; it overrides the theme."
        } else {
            $notes += "Customize in $($entries[$entries.Count - 1]) (the last file in LG_CONFIG_FILE); it is loaded after the theme and overrides it."
        }
        $notes += "For matching colors, set your terminal background to #181818 and use the ANSI palette from extras/ ($RepoUrl/tree/main/extras)."
        Write-Summary $notes
    }

    # ---------------------------------------------------------------- append mode

    function Invoke-AppendInstall {
        $themeText = Get-ThemeText
        [void][System.IO.Directory]::CreateDirectory($TargetDir)
        $blockText = $Latin1.GetString($Utf8NoBom.GetBytes($BeginMarker + "`n" + $themeText + $EndMarker + "`n"))

        $exists = Test-FileExists $ConfigFile
        $oldText = ''
        if ($exists) { $oldText = Read-ConfigText $ConfigFile }
        $wide = Get-WideEncodingName $oldText
        if ($wide) {
            throw ("$Prefix Append mode refused: $ConfigFile is saved as $wide (Windows PowerShell's > and Out-File write UTF-16), and the theme block is UTF-8, so appending would break it. Nothing was changed. " +
                "Either use overlay mode (run this installer without -Mode Append), or re-save config.yml as UTF-8 and run again.")
        }
        $lines = @(Get-ConfigLines $oldText)
        $blocks = @(Find-MarkerBlocks $lines)
        $broken = @($blocks | Where-Object { $_.End -lt 0 })
        if ($broken.Count -gt 0) {
            throw "$Prefix $ConfigFile has a '$BeginMarker' line (line $($broken[0].Start + 1)) without a matching '$EndMarker' line. Fix or remove it by hand, then run again. Nothing was changed."
        }

        if ($blocks.Count -gt 0) {
            $newText = Join-WithoutBlocks $lines $blocks $blockText
            $action = 'Replaced the theme block in'
            if (Test-TopLevelGui $lines $blocks) {
                Write-Warn "$ConfigFile has another top-level gui: key outside the theme block; lazygit refuses to start with two gui: keys. Merge them, or switch to overlay mode (run with -Uninstall, then install without -Mode Append)."
            }
        } elseif (Test-TopLevelGui $lines $blocks) {
            throw ("$Prefix Append mode refused: $ConfigFile already has a top-level gui: key, and a second one would stop lazygit from starting. Nothing was changed. " +
                "Either use overlay mode (run this installer without -Mode Append), or paste the theme's theme: block (and border: single) under your existing gui: key by hand: $RepoUrl/blob/main/themes/$ThemeId.yml")
        } else {
            $newText = $oldText
            if ($newText.Length -gt 0 -and -not $newText.EndsWith("`n", [System.StringComparison]::Ordinal)) {
                if ($newText.Contains("`r`n")) { $newText += "`r`n" } else { $newText += "`n" }
            }
            $newText += $blockText
            $action = 'Appended the theme block to'
        }

        if (Test-SameText $newText $oldText) {
            Write-Info "The theme block in $ConfigFile is already up to date."
        } else {
            if ($exists -and $oldText.Length -gt 0) { Backup-ConfigFile }
            Write-ConfigText $ConfigFile $newText
            Add-Change "$action $ConfigFile (between the '$BeginMarker' and '$EndMarker' lines)"
        }

        # lazygit only reads config.yml when LG_CONFIG_FILE is unset or lists it.
        if ($NoPersist) {
            $effective = [string]$env:LG_CONFIG_FILE
        } else {
            $effective = Get-StoredValue 'User'
            if (@(Split-ConfigList $effective).Count -eq 0) {
                $effective = Get-StoredValue 'Machine'
            }
        }
        $effectiveEntries = @(Split-ConfigList $effective)
        if ($effectiveEntries.Count -gt 0 -and @($effectiveEntries | Where-Object { Test-SamePath $_ $ConfigFile }).Count -eq 0) {
            Write-Warn "LG_CONFIG_FILE is set to $effective and does not list $ConfigFile, so lazygit will not read the theme block. Add $ConfigFile to LG_CONFIG_FILE or use overlay mode."
        }

        $notes = @()
        $notes += "To undo: $(Get-UndoCommand)"
        $notes += 'Next: restart lazygit.'
        $notes += "For matching colors, set your terminal background to #181818 and use the ANSI palette from extras/ ($RepoUrl/tree/main/extras)."
        Write-Summary $notes
    }

    # ---------------------------------------------------------------- uninstall

    # Order: LG_CONFIG_FILE first, then config.yml, the theme file last. If a step fails, no
    # LG_CONFIG_FILE is left listing a theme file that is already gone.
    function Invoke-Uninstall {
        $processValue = [string]$env:LG_CONFIG_FILE
        $processNew = Get-UninstallValue $processValue ''
        # Read even with -NoPersist: a value this run leaves alone must not lose its theme file.
        $user = Get-StoredValue 'User'
        $machine = Get-StoredValue 'Machine'
        if (-not $NoPersist) {
            $userNew = Get-UninstallValue $user $machine
            if ($null -ne $userNew) {
                if ($userNew -eq '') {
                    Remove-UserVariable
                    Add-Change "Deleted the User environment variable LG_CONFIG_FILE (was: $user)"
                } else {
                    Set-UserValue $userNew
                    Add-Change "Set the User environment variable LG_CONFIG_FILE = $userNew (theme entry removed)"
                }
            }
        }
        if ($null -ne $processNew) {
            if ($processNew -eq '') {
                Remove-Item -LiteralPath 'Env:LG_CONFIG_FILE' -ErrorAction SilentlyContinue
                if ($NoPersist) { Add-Change 'Removed LG_CONFIG_FILE from this PowerShell process (-NoPersist)' }
            } else {
                $env:LG_CONFIG_FILE = $processNew
                if ($NoPersist) { Add-Change "Set LG_CONFIG_FILE for this PowerShell process only (-NoPersist): $processNew" }
            }
        }

        if (Test-FileExists $ConfigFile) {
            $oldText = Read-ConfigText $ConfigFile
            $wide = Get-WideEncodingName $oldText
            if ($wide) {
                if ($oldText.Contains($BeginMarker) -or (Read-ConfigScanText $ConfigFile).Contains($BeginMarker)) {
                    Write-Warn "$ConfigFile is saved as $wide and contains a '$BeginMarker' line; left unchanged, since editing it byte-wise would break it. Remove the theme block by hand."
                }
            } else {
                $lines = @(Get-ConfigLines $oldText)
                $blocks = @(Find-MarkerBlocks $lines)
                $broken = @($blocks | Where-Object { $_.End -lt 0 })
                if ($broken.Count -gt 0) {
                    Write-Warn "$ConfigFile has a '$BeginMarker' line (line $($broken[0].Start + 1)) without a matching '$EndMarker' line; left unchanged. Remove the theme block by hand."
                } elseif ($blocks.Count -gt 0) {
                    Backup-ConfigFile
                    Write-ConfigText $ConfigFile (Join-WithoutBlocks $lines $blocks '')
                    Add-Change "Removed the theme block from $ConfigFile"
                }
            }
        }

        # lazygit refuses to start while a listed file is missing: keep the theme file while an
        # LG_CONFIG_FILE this run does not change still lists it.
        $keepTheme = $false
        if ($NoPersist -and (Test-ListsTheme $user)) {
            $keepTheme = $true
            Write-Warn "The User environment variable LG_CONFIG_FILE still lists $ThemeDest, and -NoPersist leaves it alone, so the theme file was kept (lazygit would refuse to start without it). To remove the theme completely, run again without -NoPersist."
        }
        if (Test-ListsTheme $machine) {
            $keepTheme = $true
            Write-Warn "The Machine-wide LG_CONFIG_FILE lists $ThemeDest, so the theme file was kept (lazygit would refuse to start without it). Remove that entry from an elevated prompt, then run -Uninstall again."
        }
        if (-not $keepTheme) {
            if (Test-FileExists $ThemeDest) {
                Remove-Item -LiteralPath $ThemeDest -Force
                Add-Change "Removed $ThemeDest"
            }
            if (Test-Path -LiteralPath $ThemesDir -PathType Container) {
                if (@(Get-ChildItem -LiteralPath $ThemesDir -Force).Count -eq 0) {
                    Remove-Item -LiteralPath $ThemesDir -Force
                    Add-Change "Removed the empty directory $ThemesDir"
                }
            }
        }

        $notes = @()
        if (Test-FileExists $ConfigFile) { $notes += "Kept $ConfigFile (your settings are never deleted)." }
        if (-not $NoPersist) {
            $notes += 'Next: open a NEW terminal (running programs keep the old environment), then restart lazygit.'
        }
        Write-Summary $notes
    }

    # ---------------------------------------------------------------- main

    if (-not (Test-IsWindowsHost)) {
        Write-Host "$Prefix This is the Windows installer. On macOS/Linux use install.sh instead:"
        Write-Host "  $ShInstall"
        return
    }

    # Harmless here; keeps any future download on TLS 1.2 in Windows PowerShell 5.1.
    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
    } catch { }

    if ($ConfigDir) {
        $rawDir = $ConfigDir
        $dirSource = '-ConfigDir'
    } else {
        $rawDir = Get-LazygitConfigDir
        $dirSource = 'lazygit --print-config-dir'
        if (-not $rawDir) {
            $rawDir = Get-DefaultConfigDir
            if ($env:CONFIG_DIR) { $dirSource = 'CONFIG_DIR' } else { $dirSource = "lazygit's default lookup" }
            if (Get-Command -Name 'lazygit' -CommandType Application -ErrorAction SilentlyContinue) {
                Write-Warn "lazygit --print-config-dir gave no usable answer, so the config directory was worked out the way lazygit does it: $rawDir. If lazygit uses another one, run again with -ConfigDir <dir>."
            } else {
                Write-Warn "lazygit is not on PATH (just installed it? open a new terminal), so the config directory was worked out the way lazygit does it: $rawDir. If lazygit uses another one, run again with -ConfigDir <dir>."
            }
        }
    }
    $TargetDir  = Resolve-FullPath $rawDir
    $ConfigFile = [System.IO.Path]::Combine($TargetDir, 'config.yml')
    $ThemesDir  = [System.IO.Path]::Combine($TargetDir, 'themes')
    $ThemeDest  = [System.IO.Path]::Combine($ThemesDir, "$ThemeId.yml")

    Write-Info "lazygit config directory: $TargetDir (from $dirSource)"
    if ($TestEnvKey) { Write-Info "Test mode: the User/Machine LG_CONFIG_FILE values are kept under $TestEnvKey (LGVDM_TEST_ENV_KEY)." }

    if ($Uninstall) {
        Invoke-Uninstall
    } elseif ($Mode -eq 'Append') {
        Invoke-AppendInstall
    } else {
        Invoke-OverlayInstall
    }
}

try {
    Install-LazygitVSCodeDarkModern -Uninstall:$Uninstall -Mode $Mode -ConfigDir $ConfigDir -NoPersist:$NoPersist
} finally {
    Remove-Item -LiteralPath 'Function:\Install-LazygitVSCodeDarkModern' -ErrorAction SilentlyContinue
}
