#!/bin/sh
# tools/sync-theme.sh - embed the complete theme catalog in both installers.
#
#   sh tools/sync-theme.sh           rewrite generated regions
#   sh tools/sync-theme.sh --check   fail when a generated region is stale

set -eu

say() { printf '[sync-theme] %s\n' "$*"; }
die() { printf '[sync-theme] ERROR: %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<'EOF'
Usage: sh tools/sync-theme.sh [--check]

Regenerates the embedded catalog and every theme in install.sh and install.ps1
from themes/catalog.txt and themes/<id>.yml.

  --check   Only compare; exit 1 if either installer is out of date.
EOF
}

check_theme() {
  _ct_id=$1
  _ct_file=$ROOT/themes/$_ct_id.yml
  [ -s "$_ct_file" ] || die "missing or empty theme: $_ct_file"
  [ -s "$ROOT/extras/windows-terminal/$_ct_id.json" ] || die "missing terminal palette: extras/windows-terminal/$_ct_id.json"
  grep -q '"name"[[:space:]]*:' "$ROOT/extras/windows-terminal/$_ct_id.json" ||
    die "terminal palette for $_ct_id has no name property"
  LC_ALL=C awk -v BINMODE=3 -v id="$_ct_id" '
    /\r/ { bad = "has CRLF line endings"; exit }
    /[^\t -~]/ { bad = "contains non-ASCII bytes (install.ps1 must remain ASCII)"; exit }
    $0 == "# END EMBEDDED CATALOG" || index($0, sprintf("%c@", 39)) == 1 { bad = "would end an embedded PowerShell string"; exit }
    $0 == "LGVDM_CATALOG_EOF" || $0 == ("LGVDM_THEME_" id "_EOF") { bad = "would end an embedded shell here-document"; exit }
    END { if (bad) { print bad > "/dev/stderr"; exit 1 } }' "$_ct_file" ||
    die "$_ct_file cannot be embedded safely"
  [ -z "$(tail -c 1 "$_ct_file")" ] || die "$_ct_file must end with exactly one newline"
  [ -n "$(tail -n 1 "$_ct_file")" ] || die "$_ct_file must not end with a blank line"
}

load_catalog() {
  CATALOG=$ROOT/themes/catalog.txt
  [ -f "$CATALOG" ] || die "themes/catalog.txt not found"
  THEME_IDS=''
  while IFS='|' read -r _lc_id _lc_name _lc_extra || [ -n "$_lc_id$_lc_name$_lc_extra" ]; do
    _lc_id=$(printf '%s' "$_lc_id" | tr -d '\r' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    _lc_name=$(printf '%s' "$_lc_name" | tr -d '\r' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    _lc_extra=$(printf '%s' "$_lc_extra" | tr -d '\r')
    [ -n "$_lc_id" ] || continue
    [ "${_lc_id#\#}" = "$_lc_id" ] || continue
    printf '%s\n' "$_lc_id" | grep -Eq '^[a-z0-9]$|^[a-z0-9]([a-z0-9-]*[a-z0-9])$' || die "invalid catalog ID: $_lc_id"
    if printf '%s\n' "$_lc_id" | grep -q -- '--'; then die "invalid catalog ID: $_lc_id"; fi
    [ -n "$_lc_name" ] && [ -z "$_lc_extra" ] || die "invalid catalog line for $_lc_id (expected id|display name)"
    if printf '%s\n' " $THEME_IDS " | grep -Fq " $_lc_id "; then die "duplicate catalog ID: $_lc_id"; fi
    check_theme "$_lc_id"
    THEME_IDS="${THEME_IDS}${THEME_IDS:+ }$_lc_id"
  done <"$CATALOG"
  [ -n "$THEME_IDS" ] || die "the theme catalog is empty"
}

emit_catalog_rows() {
  while IFS= read -r _ec_line || [ -n "$_ec_line" ]; do
    [ -n "$_ec_line" ] || continue
    [ "${_ec_line#\#}" = "$_ec_line" ] || continue
    printf '%s\n' "$_ec_line"
  done <"$CATALOG"
}

theme_delimiter() { printf '%s' "$1" | tr '[:lower:]-' '[:upper:]_'; }

generate_region() {
  _gr_kind=$1
  _gr_out=$2
  {
    printf '%s\n' '# BEGIN EMBEDDED CATALOG (generated by tools/sync-theme.sh - do not edit by hand)'
    if [ "$_gr_kind" = ps1 ]; then
      printf '%s\n' "\$EmbeddedCatalog = @'"
      emit_catalog_rows
      printf '%s\n' "'@"
      # shellcheck disable=SC2016 # literal PowerShell source for the generated installer
      printf '%s\n' '$EmbeddedThemes = @{'
      for _gr_id in $THEME_IDS; do
        printf "    '%s' = @'\n" "$_gr_id"
        cat "$ROOT/themes/$_gr_id.yml"
        printf '%s\n' "'@"
      done
      printf '%s\n' '}'
    else
      printf '%s\n' 'embedded_catalog() {'
      printf '%s\n' "cat <<'LGVDM_CATALOG_EOF'"
      emit_catalog_rows
      printf '%s\n' 'LGVDM_CATALOG_EOF'
      printf '%s\n' '}'
      printf '%s\n' 'embedded_theme() {'
      # shellcheck disable=SC2016 # literal shell source for the generated installer
      printf '%s\n' '  case $1 in'
      for _gr_id in $THEME_IDS; do
        _gr_delim=$(theme_delimiter "$_gr_id")
        printf '    %s)\n' "$_gr_id"
        printf "      cat <<'LGVDM_THEME_%s_EOF'\n" "$_gr_delim"
        cat "$ROOT/themes/$_gr_id.yml"
        printf 'LGVDM_THEME_%s_EOF\n' "$_gr_delim"
        printf '%s\n' '      ;;'
      done
      printf '%s\n' '    *) return 1 ;;'
      printf '%s\n' '  esac'
      printf '%s\n' '}'
    fi
    printf '%s\n' '# END EMBEDDED CATALOG'
  } >"$_gr_out"
}

# Replace either the catalog region or the single-theme region used by older
# snapshots. All content outside the region stays untouched.
replace_region() {
  _rr_target=$1
  _rr_region=$2
  _rr_out=$3
  LC_ALL=C awk -v R="$_rr_region" '
    function is_begin(s) { return s ~ /^[[:space:]]*# BEGIN EMBEDDED (CATALOG|THEME)/ }
    function is_end(s) { return s ~ /^[[:space:]]*# END EMBEDDED (CATALOG|THEME)/ }
    BEGIN { while ((getline x < R) > 0) generated[++n] = x; close(R) }
    {
      line = $0; sub(/\r$/, "", line)
      if (!inside && is_begin(line)) {
        for (i = 1; i <= n; i++) print generated[i]
        inside = 1
        replaced = 1
        next
      }
      if (inside) {
        if (is_end(line)) inside = 0
        next
      }
      print $0
    }
    END { if (inside || !replaced) exit 3 }' "$_rr_target" >"$_rr_out"
}

sync_one() {
  _so_kind=$1
  _so_target=$2
  _so_region=$TMP_DIR/$_so_kind.region
  _so_out=$TMP_DIR/$_so_kind.out
  generate_region "$_so_kind" "$_so_region"
  replace_region "$_so_target" "$_so_region" "$_so_out" || die "$_so_target has no complete embedded catalog region"
  if cmp -s "$_so_target" "$_so_out"; then
    say "${_so_target##*/}: embedded catalog is up to date"
  elif [ "$CHECK" = 1 ]; then
    die "${_so_target##*/}: embedded catalog is OUT OF DATE; run: sh tools/sync-theme.sh"
  else
    cat "$_so_out" >"$_so_target"
    say "${_so_target##*/}: embedded catalog updated"
  fi
}

main() {
  CHECK=0
  while [ $# -gt 0 ]; do
    case $1 in
      --check) CHECK=1 ;;
      -h | --help) usage; exit 0 ;;
      *) usage >&2; die "unknown option: $1" ;;
    esac
    shift
  done
  case $0 in */*) _dir=${0%/*} ;; *) _dir=. ;; esac
  ROOT=$(CDPATH='' cd -- "$_dir/.." && pwd) || die "cannot find repository root"
  TMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/sync-theme.XXXXXX") || die "mktemp failed"
  trap 'rm -rf "$TMP_DIR"' EXIT HUP INT TERM
  load_catalog
  sync_one sh "$ROOT/install.sh"
  sync_one ps1 "$ROOT/install.ps1"
}

main "$@"
